### ISSUE TITLE
great to use except - for one little thingy

### ISSUE THREAD

**Issue by sigoa** [g1itch/PyBitmessage#1]
the Qt5 branch is great to look at on low-dpi screens! better than the original under Qt4.
only thing is: one cannot generate new addresses, pls use the current v0.6 sources from P Surda, that ought to work. err msg is:

 File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner ##    self.run()
 File "...../glitchQT5/src/class_addressGenerator.py", line 231, in run
    deterministicPassphrase + encodeVarint(signingKeyNonce)).digest()[:32]
     UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

with that fixed, the Qt5 is totally excellent !

**Comment by g1itch** [comment]
fixed in 03b0c9e2d9fee341a6b4c51e4a5a5b23be793155
